// <auto-generated />
using System;
using CoreGraphQL.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreGraphQL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190920044518_CoreGraphQL.Entities.Context.ApplicationContext")]
    partial class CoreGraphQLEntitiesContextApplicationContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreGraphQL.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("OwnerId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e338cc81-998d-4ed3-a483-4afd9fb2d01a"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("1dbcc8b7-ee10-4d0e-97ce-f4edfed39dcb"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("cef5354e-0bfb-4840-964d-8cd34bc19888"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("0480cd10-99f9-4af7-9224-3b262933d196"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("d49293f7-e78f-4fd1-ab65-50be715d31f1"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("0480cd10-99f9-4af7-9224-3b262933d196"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("CoreGraphQL.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1dbcc8b7-ee10-4d0e-97ce-f4edfed39dcb"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("0480cd10-99f9-4af7-9224-3b262933d196"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("CoreGraphQL.Entities.Account", b =>
                {
                    b.HasOne("CoreGraphQL.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
