// <auto-generated />
using System;
using CoreGraphQL.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreGraphQL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190920044037_up-initialmigration")]
    partial class upinitialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreGraphQL.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("OwnerId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fbc5808-ae02-48b0-a60e-d73745404898"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("4b94cdb4-5350-49a3-a30f-1ef7e6a3b572"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("6bab6517-a8e7-4738-b5fb-26184a084ae0"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("e676d0c8-8e7f-499d-8df1-7ca69856b502"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("56e87a0c-15bb-4f26-8ce2-147a37e242f4"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("e676d0c8-8e7f-499d-8df1-7ca69856b502"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("CoreGraphQL.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b94cdb4-5350-49a3-a30f-1ef7e6a3b572"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("e676d0c8-8e7f-499d-8df1-7ca69856b502"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("CoreGraphQL.Entities.Account", b =>
                {
                    b.HasOne("CoreGraphQL.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
