// <auto-generated />
using System;
using CoreGraphQL.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreGraphQL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190920043657_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreGraphQL.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("OwnerId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("168a0f4c-3dc5-4372-8c88-a0fb59f98091"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("e8dbfd03-83b8-45ec-9da4-b55ba2ccd4e7"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("fc167e87-b12e-45b0-aeae-4836c797ea91"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("e460e195-704d-45dd-9d4e-43c83dd6697d"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("be34a409-476a-426e-b57d-d3f6d0d79bf9"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("e460e195-704d-45dd-9d4e-43c83dd6697d"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("CoreGraphQL.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8dbfd03-83b8-45ec-9da4-b55ba2ccd4e7"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("e460e195-704d-45dd-9d4e-43c83dd6697d"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("CoreGraphQL.Entities.Account", b =>
                {
                    b.HasOne("CoreGraphQL.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
